### ISSUE TITLE
Falta () na penultima resposta

### ISSUE THREAD

**Issue by Viniuau** [Holzlsauer/quarentenadev#1]
Na pergunta da Maria, faltou os parenteses na soma das balas.

alert("Maria tem agora " + 19+45 + " balas.");
output: Maria tem agora 1945 balas.

alert("Maria tem agora " + (19+45) + " balas.");
output: Maria tem agora 64 balas.

Bons estudos!

**Comment by Holzlsauer** [comment]
Muito bem observado!
Vou corrigir, obrigado por avisar 😁
